### ISSUE TITLE
Negocios - Modificacion del metodo createShop

### ISSUE THREAD

**Issue by GastonZianni** [SantaPesca/users#24]
El metodo deberia retornar en el body del post un object que tenga el siguiente formato:
```
{
   id: <idNegocio> (integer),
   name: <NombreNegocio> (string)
}
```

**Comment by midestefanis** [comment]
![image](https://user-images.githubusercontent.com/59846928/81618896-b6503300-93be-11ea-952a-ad2d41722024.png)
