### ISSUE TITLE
Negocios - eliminación de una foto temporal

### ISSUE THREAD

**Issue by PedroCapdevila** [SantaPesca/users#36]
Cuando el usuario elimine una foto del carrete de fotos cuando crea un negocio se debe mandar un request para eliminarla de la carpeta temporal:

method: DELETE
path: .../users/shop/tmpPhoto/{idTemporalFolder}/{fileName}.

Atributos:
idTemporalFolder: (long integer). Carpeta que contendra todas las fotos que corresponden a un negocio.
fileName: (string). Nombre de la foto a borrar

**Comment by midestefanis** [comment]
Fue implementado el endpoint. Ej: 
Una vez subida una foto temporal si el usuario la elimina se debe hacer una request como esta:

curl -XDELETE -H "Authorization: Bearer {token}" http://localhost:8005/shop/tmpPhoto/1591463936896/photo509386752746072695.jpg

En caso de que esa foto no se encuentre en el server por algun motivo raro devuelve:
Error 404 en el header y como mensaje `{"message":"NOT_FOUND"}`

Te asigno a vos @GastonZianni  para que lo termines de implementar en el front y lo pruebes
