### ISSUE TITLE
Login - Creacion del metodo para validar el token almacenado

### ISSUE THREAD

**Issue by GastonZianni** [SantaPesca/users#50]
Metodo: GET,
Nombre: ...users/validate, (o cambien el nombre, yo para no poner /login/validate porque no es un login),
Resultado esperado:
```
{
    permissions: {
        actions: <Array de acciones>,
        subjects: <Array de subjects>
}
```

Se debera analizar si el token que va en el header es valido o no.
Debe devolver los permisos si es valido. En caso contrario debera devolver UNAUTHORIZED en el body como venimos haciendo

**Comment by midestefanis** [comment]
Se cambió el nombre del endpoint a **...users/validateToken** 

cc @GastonZianni

**Comment by midestefanis** [comment]
Ej de una petición erronea:

```
curl -XGET -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmVsb3BlciJ9.K2PJDVnPD_xNPSMIhbPw4ihnl0fMYsfM3w283G7CcpM" http://localhost:8005/permissions
{"message":"UNAUTHORIZED"}
```

Ej de una petición con una sesión en redis:

```
curl -XGET -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmVsb3BlciIsImp0aSI6Ijg4NjYwYzc4LWZmZGUtNDUxOS05NGUyLTIwNWIyMzA0YTg4YSJ9.ffgsDXhDFipt-SW3ouW3qQ9-fYvfbhFh035jmKklxCk" http://localhost:8005/permissions
{"permissions":{"actions":["manage"],"subjects":["all"]}}
```

Hubo una refactorización más @GastonZianni cambiamos el endpoint nuevamente a:
**...users/permissions**
Era más correcto ya que lo que hicimos fue:
Llega el token en el header y no lo validamos porque ese token ya fue validado si es que está en Redis. Entonces lo que hacemos es ir a Redis y fijarse si está ahi. Si está, siginifica que hay una sesión activa para ese token. Luego vamos a la db a buscar los roles del usuario y lo devolvemos.
