### ISSUE TITLE
Fotos - Subir fotos al perfil del usuario

### ISSUE THREAD

**Issue by PedroCapdevila** [SantaPesca/users#61]
# Request

Cuando el usuario suba una foto a su perfil se mandará un request `multipart` con dicha foto:

Datos del request:

```text
Method: POST
Path: .../users/photo
Atributos:
  - fileName: (string)
  - idSpecie: (numero o string vacio)
```

# Lógica

Una vez que se realice el request los pasos son:

1. Tomar el ID del usuario con el email que viaja en el JWT del header (se podría usar el email del usuario también).
2. Crear la carpeta dentro del bucket y guardar la URL de dicha carpeta (y otros datos importantes de la foto) en MongoDB. La carpeta tendrá como nombre el ID del usuario (o el email). Si la carpeta ya existe omitir paso.
3. Subir la foto a la carpeta.
4. Responder con un 200 y algún dato de utilidad (podría ser la URL de la carpeta).

# Tareas

- [x] Generar bucket `users_photos`.
- [ ] Implementar controlador `UploadUserPhoto` que realice la lógica mencionada.

**Comment by GastonZianni** [comment]
@PedroCapdevila @midestefanis se agrega el atributo idEspecie porque lo vamos a necesitar segun el mock-up del perfil del usuario.
**ACLARACION: En la imagen que esta subida a docker, el post que se manda cuando el usuario guarda una captura NO tiene este nuevo atributo**

**Comment by GastonZianni** [comment]
Ya esta implementado en la imagen actual de Docker
